// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-G7snzbFSbMdpT0cjXokrKDxshh-PCg',
    appId: '1:732937293793:web:febaef4a8f8f2eeaf74ca0',
    messagingSenderId: '732937293793',
    projectId: 'control-c0466',
    authDomain: 'control-c0466.firebaseapp.com',
    storageBucket: 'control-c0466.appspot.com',
    measurementId: 'G-7ZPXX4T88G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjP_eQ0jYaVuBRxo0dbtpXjMkTBrEHhvw',
    appId: '1:732937293793:android:eab7172e44f327ecf74ca0',
    messagingSenderId: '732937293793',
    projectId: 'control-c0466',
    storageBucket: 'control-c0466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JWWGXhsykiZxlNvhxewrxcg5LmX1KcY',
    appId: '1:732937293793:ios:0cf879dc2c6169eaf74ca0',
    messagingSenderId: '732937293793',
    projectId: 'control-c0466',
    storageBucket: 'control-c0466.appspot.com',
    iosClientId: '732937293793-cas6ieep26e68othfe1n5vr82fqb90ib.apps.googleusercontent.com',
    iosBundleId: 'com.fiico.app',
  );
}
